# 1. Información del Taller
site_name: Tips de Cristo
site_description: Apuntes de fácil acceso para distintas tecnologías.
site_author: Cristóbal Contreras Rubio
site_url: https://crisconru.github.io/
# 2. Repositorio
repo_name: crisconru/tips
repo_url: https://github.com/crisconru/tips
edit_uri: ""
# edit_uri: edit/main/docs/
# 3. Footer
copyright: Copyright &copy; 2019 - 2022 Cristóbal Contreras
extra:
  # Footer - Show Made with MkDocs
  generator: false
  # Footer - Icons
  social:
    # Blog
    # Github
    - icon: fontawesome/brands/github
      link: https://github.com/crisconru
      name: Github de Cristo
    # Twitter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crisconru
      name: Github de Cristo
    # Linkedin
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/cristobalcontrerasrubio
      name: Github de Cristo
# 4. Navegación
nav:
  - Contenido: index.md # TODO: Reodernar todo bien
  - Web:
    - Frontend:
      - HTML: web/frontend/html/html-indice.md
      - CSS:  # TODO:
        - Plugins: web/frontend/css/css-plugins.md
      - VanillaJS: web/frontend/js/js-indice.md
    - Backend:
      - Django:
        - Principiante: web/backend/django/principiante.md
        - Intermedio: web/backend/django/intermedio.md
        - Avanzado: web/backend/django/avanzado.md
  - Hardware:
    - Micropython: hw/upython/upython-informacion.md
    - Platformio: hw/pio/pio-informacion.md
  - IoT:
    - MQTT: iot/mqtt/mqtt.md
    # - RabbitMQ: TODO:
  - Software:
    - IDEs:
      - Visual Studio code: sw/ides/vscode/vscode.md
    - Python:
      - Entornos virtuales:
        - Introducción: sw/python/venv/venv-introduccion.md
        - virtualenv: sw/python/venv/venv-virtualenv.md
        - virtualenvwrapper: sw/python/venv/venv-virtualenvwrapper.md
        - pipenv: sw/python/venv/venv-pipenv.md
        - pyenv: sw/python/venv/venv-pyenv.md
      - PYTHONPATH: sw/python/python-pythonpath.md
  - Devops:
    - Git: 
      - Comandos: devops/git/git.md
      - Git Flow: devops/git/gitflow/gitflow-gitflow.md
    - Docker: # TODO: Reodernar y dejar solo lo que a mi me interesa -> Instalacion, montarc cosas, docker save-load export-import, portainer dockstation...
      - Aclaraciones: devops/docker/docker-aclaraciones.md
      - Instalación: devops/docker/docker-instalacion.md
      - Docker Hub: devops/docker/docker-hub.md
      - Comandos docker: devops/docker/docker-comandos.md
      - Lanzar contenedores: devops/docker/docker-contenedores.md
      - Crear imágenes: devops/docker/docker-imagenes.md
      - Dockerfile: devops/docker/docker-dockerfile.md
      - Volumes: devops/docker/docker-volumes.md
      - Network: devops/docker/docker-network.md
      - Docker Compose: devops/docker/docker-dockercompose.md
    - Ansible: devops/ansible/ansible.md
    # - ELK: devops/elk/elk.md
  - Linux:
    - Comandos:
      - Fecha y Hora: linux/comandos/linux-fecha-hora.md
      - Ficheros: linux/comandos/linux-ficheros.md
    - Redes:
      - Linux: linux/redes/redes-linux.md
      - SSH: linux/redes/redes-ssh.md
      - iptables: linux/redes/redes-iptables.md
      - IPv6: linux/redes/redes-ipv6.md
    - Terminal:
      - ZSH: linux/terminal/zsh.md
      - Bash Scripting: linux/terminal/terminal-bash.md
      - TMUX: 
        - Comandos: linux/terminal/tmux/tmux-comandos.md
        - Customización: linux/terminal/tmux/tmux-customizar.md

# 5. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
# 6. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Modo Oscuro
      primary: green
      accent: pink
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Claro
      primary: green
      accent: pink
  # Fuente
  font:
    text: Roboto
    code: Roboto Mono
  # Lenguage
  language: es
  #logo: img/favicon.png
  #favicon: img/favicon.png
  # Caracteristicas especiales
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # Experimental
    - search.suggest
    - search.highlight
    - search.share
  # Icono del repo
  icon:
    repo: fontawesome/brands/github
# 7. Extensiones
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# 8. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  - plugins/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# 9. Plugins
plugins:
  - search:
      lang: es
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true
