# 1. Información del Taller
site_name: Tips de Cristo
site_description: Apuntes de fácil acceso para distintas tecnologías.
site_author: Cristóbal Contreras Rubio
site_url: https://crisconru.github.io/
# 2. Repositorio
repo_name: crisconru/tips
repo_url: https://github.com/crisconru/tips
edit_uri: ""
# edit_uri: edit/main/docs/
# 3. Footer
copyright: Copyright &copy; 2019 - 2022 Cristóbal Contreras
extra:
  # Footer - Show Made with MkDocs
  generator: false
  # Footer - Icons
  social:
    # Blog
    # Github
    - icon: fontawesome/brands/github
      link: https://github.com/crisconru
      name: Github de Cristo
    # Twitter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crisconru
      name: Github de Cristo
    # Linkedin
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/cristobalcontrerasrubio
      name: Github de Cristo
# 4. Navegación
nav:
  - Contenido: index.md
  - Code:
    - Devops:
      - Ansible:
        - Ansible: code/devops/ansible/ansible.md
        - Inventario: code/devops/ansible/inventario.md
        - Comandos: code/devops/ansible/comandos.md
        - Configuracion: code/devops/ansible/configuracion.md
        - Playbooks:
          - Playbook: code/devops/ansible/playbook/playbook.md
      - Docker:
        - Aclaraciones: code/devops/docker/docker-aclaraciones.md
        - Instalación: code/devops/docker/docker-instalacion.md
        - Docker Hub: code/devops/docker/docker-hub.md
        - Comandos docker: code/devops/docker/docker-comandos.md
        - Lanzar contenedores: code/devops/docker/docker-contenedores.md
        - Crear imágenes: code/devops/docker/docker-imagenes.md
        - Dockerfile: code/devops/docker/docker-dockerfile.md
        - Volumes: code/devops/docker/docker-volumes.md
        - Network: code/devops/docker/docker-network.md
        - Docker Compose: code/devops/docker/docker-dockercompose.md
      - ELK:
        - code/devops/elk/elk.md
      - Git: code/devops/git/git-git.md
      - Git Flow:
          - Git Flow: code/devops/git/gitflow/gitflow-gitflow.md
          - Puesta a punto: code/devops/git/gitflow/gitflow-instalacion.md
          - Comandos: code/devops/git/gitflow/gitflow-comandos.md
    - IDEs:
      - Visual Studio code: code/ides/vscode/vscode.md
    - Python:
      - Entornos virtuales:
        - Introducción: code/python/venv/venv-introduccion.md
        - virtualenv: code/python/venv/venv-virtualenv.md
        - virtualenvwrapper: code/python/venv/venv-virtualenvwrapper.md
        - pipenv: code/python/venv/venv-pipenv.md
        - pyenv: code/python/venv/venv-pyenv.md
      - PYTHONPATH: code/python/python-pythonpath.md
    - Web:
      - Frontend:
        - HTML: code/web/frontend/html/html-indice.md
        - CSS:
          - Plugins: code/web/frontend/css/css-plugins.md
        - JS: code/web/frontend/js/js-indice.md
      - Backend:
        - Django:
          - Django: code/web/backend/django/django.md
          - Principiante: code/web/backend/django/django-principiante.md
          - Intermedio: code/web/backend/django/django-intermedio.md
          - Avanzado: code/web/backend/django/django-avanzado.md
  - Software:
    - Linux:
      - Fecha y Hora: sw/linux/linux-fecha-hora.md
      - Ficheros: sw/linux/linux-ficheros.md
    - Redes:
      - Linux: sw/redes/redes-linux.md
      - SSH: sw/redes/redes-ssh.md
      - iptables: sw/redes/redes-iptables.md
      - IPv6: sw/redes/redes-ipv6.md
    - Terminal:
      - Bash: sw/terminal/terminal-bash.md
      - tmux: 
        - Comandos: sw/terminal/tmux/tmux-comandos.md
        - Customización: sw/terminal/tmux/tmux-customizar.md
      - ZSH: sw/terminal/terminal-zsh.md
  - Hardware:
    - Micropython: hw/upython/upython-informacion.md
    - Platformio: hw/pio/pio-informacion.md
  - IoT:
    - MQTT:
      - MQTT: iot/mqtt/mqtt.md
      - Hola mundo: iot/mqtt/mqtt-hello-world.md

# 5. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
# 6. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Modo Oscuro
      primary: green
      accent: pink
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Claro
      primary: green
      accent: pink
  # Fuente
  font:
    text: Roboto
    code: Roboto Mono
  # Lenguage
  language: es
  #logo: img/favicon.png
  #favicon: img/favicon.png
  # Caracteristicas especiales
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # Experimental
    - search.suggest
    - search.highlight
    - search.share
  # Icono del repo
  icon:
    repo: fontawesome/brands/github
# 7. Extensiones
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# 8. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# 9. Plugins
plugins:
  - search:
      lang: es
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
