version: '3'

services:

  nodered:
    build:
      context: ./nodered
      dockerfile: Dockerfile
    restart: always
    # user: '1000:1000'
    ports:
      - '2880:1880'
    volumes:
      - './nodered/data:/data'
